# Generated by Django 5.2.1 on 2025-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
